language: java

jdk:
  - oraclejdk8

sudo: true

before_install:
  # 赋予执行权限
  - chmod a+x gradlew

script:
  - ./gradlew build dokka
  - ./gradlew jar website
  - cd ./docs
  - git init
  - git config user.name "MechDancerProject"
  - git config user.email "berberman@mechdancer.org"
  - git add -A
  - git commit -m "`curl -s http://whatthecommit.com/index.txt`"
  - git remote add origin https://${GitHubTokenAll}@github.com/MechDancer/framework
  - git checkout -b gh-pages
  - git push origin gh-pages -f

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  # 发布到 GitHub Release
  - provider:     releases
    skip_cleanup: true
    file_glob:    true
    file:         "build/libs/*"
    api_key:      $GitHubTokenAll
    on:
      tags:       true

notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=4b59c5ece57fc88af8fda28cc07573c4caf525aa69afc0cc888ccf3ce6dbe41b